@extends('frontend.layouts.master')
@section('meta_content')
@php
    $logo=App\Helpers\MyHelper::getSiteConfig('header_site_logo');
@endphp
  <!-- HTML Meta Tags -->
  <title>{{ $page->seo_title }} - {{ config('app.name') }}</title>
  <meta name="description" content="{{ $page->seo_description }}">
  <meta name="keywords" content="{{$page->seo_keyword}}">
  <!-- Facebook Meta Tags -->
  <meta property="og:url" content="{{ url()->current() }}">
  <meta property="og:type" content="website">
  <meta property="og:title" content="{{ $page->seo_title }} - {{ config('app.name') }}">
  <meta property="og:description" content="{{ $page->seo_description }}">
  <meta property="og:image" content="{{ asset('storage/setting/' . $logo) }}">
  <meta property="og:image:alt" content="{{ $page->seo_title }} - {{ config('app.name') }} Logo">

  <!-- Twitter Meta Tags -->
  <meta name="twitter:card" content="summary_large_image">
  <meta property="twitter:domain" content="{{ url()->current() }}">
  <meta property="twitter:url" content="{{ url()->current() }}">
  <meta name="twitter:title" content="{{ $page->seo_title }} - {{ config('app.name') }}">
  <meta name="twitter:description" content="{{ $page->seo_description }}">
  <meta name="twitter:image" content="{{ asset('storage/setting/' . $logo) }}">
  <!-- Meta Tags Generated by Susan Paudel -->
@endsection

@section('css')
    <style>
        .sh-about {
            background: url("{{ asset('frontend/images/bg-content/sh-about.jpg') }}") no-repeat;

        }
    
.warp-counter .counter {
    color: #222;
}
.warp-counter p {
    color: #727272;
}
    </style>
@endsection
@section('content')
    <section class="no-padding sh-about">
        <div class="sub-header ">
            <span>COMPANY PROFILE</span>
            <h3>ABOUT US</h3>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('index') }}"><i class="fa fa-home"></i> HOME </a>
                </li>
                
                <li class="active">ABOUT US</li>
            </ol>
        </div>
    </section>


    @if(isset($page->pageContents[0]))
    <section class="no-padding">
        <div class="container">
            <div class="row">
                <div class="whyus-warp-h2 whyus-about">
                    <div class="col-md-6">
                        <div class="left-whyus-h2">
                            <div class="demo-style-1-warp">
                                <img src="{{ asset('storage/pages/'.$page->pageContents[0]->image) }}" class="img-responsive"
                                    alt="Image">
                                <div class="demo-style-1-box-text right" style="width: 50%">
                                    {{$page->pageContents[0]->title}}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="right-whyus-h2">
                            <div class="iconbox-warp ">
                                {!!$page->pageContents[0]->content??''!!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    @endif
    <!-- about description -->
   
@if(count($chooses)>0)
    <section class="no-padding bg-counter-h1">
        <div class="container">
            <div class="row">
                <div class="warp-counter">
                    @foreach ($chooses as $choose)
                    <div class="col-md-3 col-sm-6">
                        <div class="counter-inline">
                            {!!$choose->icon!!}
                            <span class="counter">{{$choose->counter}}</span>
                            <p>{{$choose->title}}</p>
                        </div>
                    </div>
                    @endforeach
                   
                   
                </div>
            </div>
        </div>
    </section>
    <!-- couterup -->
  @endif
  @if(isset($page->pageContents[1]))
    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="main-page">
                        <div class="about-founder">
                            <div class="box-img-left">
                                <div class="feature">
                                    <img src="{{ asset('storage/pages/'.$page->pageContents[1]->image) }}" class="img-responsive "
                                        alt="Image">
                                </div>
                                <div class="boxcontent">
                                    <h4>{{ $page->pageContents[1]->title }}</h4>
                                    <p>{!! $page->pageContents[1]->content !!}</p>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
               @include('frontend.layouts.sidecontent')
            </div>
        </div>
    </section>
    @endif
@endsection
