

@extends('frontend.layouts.master')
@section('css')
    <style>
        .sh-news {
            background: url("{{ asset('frontend/images/bg-content/sh-single-services.jpg') }}") no-repeat;

        }
        .feature-img-deital img{
            width:100%;
        }
    </style>
@endsection
@section('meta_content')
  <!-- HTML Meta Tags -->
  <title>{{ $blog->seo_title??$blog->title }} - {{ config('app.name') }}</title>
  <meta name="description" content="{{ $blog->seo_description }}">
  <meta name="keywords" content="{{$blog->seo_keyword}}">
  <!-- Facebook Meta Tags -->
  <meta property="og:url" content="{{ url()->current() }}">
  <meta property="og:type" content="website">
  <meta property="og:title" content="{{ $blog->seo_title }} - {{ config('app.name') }}">
  <meta property="og:description" content="{{ $blog->seo_description }}">
  <meta property="og:image" content="{{ asset('storage/blog/' . $blog->image) }}">
  <meta property="og:image:alt" content="{{ $blog->seo_title }} - {{ config('app.name') }} Logo">

  <!-- Twitter Meta Tags -->
  <meta name="twitter:card" content="summary_large_image">
  <meta property="twitter:domain" content="{{ url()->current() }}">
  <meta property="twitter:url" content="{{ url()->current() }}">
  <meta name="twitter:title" content="{{ $blog->seo_title }} - {{ config('app.name') }}">
  <meta name="twitter:description" content="{{ $blog->seo_description }}">
  <meta name="twitter:image" content="{{ asset('storage/blog/' . $blog->image) }}">
  <!-- Meta Tags Generated by Susan Paudel -->
@endsection
@section('content')

<section class="no-padding sh-news">
    <div class="sub-header ">
        <span>Blog</span>
        <h3>{{$blog->title}}</h3>
        <ol class="breadcrumb">
             <li>
                 <a href="{{route('index')}}"><i class="fa fa-home"></i> Home     </a>
             </li>
             <li>
                 <a href="{{route('blog')}}"> Blogs     </a>
             </li>
             <li class="active"> {{$blog->title}}</li>
         </ol>
    </div>
</section>
<!-- /subheader -->
    
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="new-detail-warp">
                    <div class="feature-img-deital">
                        <img src="{{ asset('storage/blog/'.$blog->image) }}" class="img-responsive" alt="Image">
                    </div>
                    <div class="new-info new-info-detail">
                        <h4>
                            <a href="{{route('blog-single',$blog->slug)}}">{{$blog->title}}</a>
                        </h4>
                        <p><i class="fa fa-calendar" aria-hidden="true"></i>{{ $blog->created_at->format('F d, Y') }}</p>
                        @php
                        $role=App\Models\User::find($blog->added_by)->name;
                        @endphp
                        @if($role)
                        <p><i class="fa fa-user" aria-hidden="true"></i> By {{$role}}</p>
                        @endif
                        {{-- <p><i class="fa fa-comments" aria-hidden="true"></i>28 </p>
                        <p>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star-half-o" aria-hidden="true"></i>
                        </p> --}}
                    </div>
                    <div class="content-detail content-new-detail">
                        {!!$blog->content!!}
                    </div>
                </div>
                {{-- <div class="footer-post">
                    <p class="tags-post">
                        <i class="fa fa-tags" aria-hidden="true"></i>
                        <a href="#">Business</a>,
                        <a href="#">Financial</a>,
                        <a href="#">Money</a>,
                        <a href="#">Loans</a>
                    </p>
                    <ul class="widget-footer-social-1 footer-post-share social-hover-defaul">
                        <li><a class="facebook" href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a class="twitter" href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a class="google" href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a class="linkedin" href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                    </ul>
                </div> --}}
            </div>
            {{-- <div class="col-md-12">
                <div class="title-block title-pd">
                    <h3>Our Tought</h3>
                    <span class="bottom-title"></span>
                </div>
                <div class="comment-list">
                    <ol>
                        <li>
                            <div class="comment-item">
                                <div class="avatar">
                                    <img src="images/Comment/1.jpg" class="img-responsive" alt="Image">
                                    <a href="#" class="reply-comment"><i class="fa fa-reply" aria-hidden="true"></i></a>
                                </div>
                                <div class="comment-detail">
                                    <h6>Fatma Mahmoud</h6>
                                    <span class="comment-info"><i class="fa fa-calendar" aria-hidden="true"></i> Posted on 5 Dec, 2015</span>
                                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae pre vitae dicta sunt explicabo. </p>
                                </div>
                            </div>
                            <ul class="child-comment">
                                <li>
                                    <div class="comment-item">
                                        <div class="avatar">
                                            <img src="images/Comment/2.jpg" class="img-responsive" alt="Image">
                                            <a href="#" class="reply-comment"><i class="fa fa-reply" aria-hidden="true"></i></a>
                                        </div>
                                        <div class="comment-detail">
                                            <h6>Amany Arafa</h6>
                                            <span class="comment-info"><i class="fa fa-calendar" aria-hidden="true"></i> Posted on 5 Dec, 2015</span>
                                            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae pre vitae dicta sunt explicabo. </p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <div class="comment-item">
                                <div class="avatar">
                                    <img src="images/Comment/3.jpg" class="img-responsive" alt="Image">
                                    <a href="#" class="reply-comment"><i class="fa fa-reply" aria-hidden="true"></i></a>
                                </div>
                                <div class="comment-detail">
                                    <h6>Jameel Rateb</h6>
                                    <span class="comment-info"><i class="fa fa-calendar" aria-hidden="true"></i> Posted on 5 Dec, 2015</span>
                                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae pre vitae dicta sunt explicabo. </p>
                                </div>
                            </div>
                        </li>
                    </ol>
                    
                </div>
            </div> --}}
        </div>
    </div>
</section>
<!-- /Main New Detail -->

{{-- <section class="bg-light-grey">
    <div class="container">	
        <div class="row">
            <div class="col-md-12">
                <div class="title-block title-contact">
                    <h3>Add Your Review</h3>
                    <span class="bottom-title"></span>
                </div>
            </div>
            <div class="form-contact-warp form-review">
                <div class="col-md-4">
                    <input type="text"   class="form-control" value="" required="required" title="" placeholder="Full Name">
                </div>
                <div class="col-md-4">
                    <input type="text"   class="form-control" value="" required="required" title="" placeholder="Email Address">
                </div>
                <div class="col-md-4">
                    <input type="text"   class="form-control" value="" required="required" title="" placeholder="Subject">
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <textarea   id="textarea" class="form-control" rows="5" required="required" placeholder="Comment"></textarea>
                    </div>
                </div>
                <div class="col-md-12">
                    <p class="rating-review">
                        <span>Your Rating</span>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                    </p>
                    <button type="submit" class="btn-main-color"> Submit Review</button>
                </div>
            </div>
        </div>
    </div>
</section> --}}
<!-- /Form reviews -->



@endsection