@extends('frontend.layouts.master')
@section('meta_content')
@php
    $logo=App\Helpers\MyHelper::getSiteConfig('header_site_logo');
@endphp
  <!-- HTML Meta Tags -->
  <title>{{ $page->seo_title }} - {{ config('app.name') }}</title>
  <meta name="description" content="{{ $page->seo_description }}">
  <meta name="keywords" content="{{$page->seo_keyword}}">
  <!-- Facebook Meta Tags -->
  <meta property="og:url" content="{{ url()->current() }}">
  <meta property="og:type" content="website">
  <meta property="og:title" content="{{ $page->seo_title }} - {{ config('app.name') }}">
  <meta property="og:description" content="{{ $page->seo_description }}">
  <meta property="og:image" content="{{ asset('storage/setting/' . $logo) }}">
  <meta property="og:image:alt" content="{{ $page->seo_title }} - {{ config('app.name') }} Logo">

  <!-- Twitter Meta Tags -->
  <meta name="twitter:card" content="summary_large_image">
  <meta property="twitter:domain" content="{{ url()->current() }}">
  <meta property="twitter:url" content="{{ url()->current() }}">
  <meta name="twitter:title" content="{{ $page->seo_title }} - {{ config('app.name') }}">
  <meta name="twitter:description" content="{{ $page->seo_description }}">
  <meta name="twitter:image" content="{{ asset('storage/setting/' . $logo) }}">
  <!-- Meta Tags Generated by Susan Paudel -->
@endsection
@section('css')
    <style>
        .sh-company-history {
            background: url("{{ asset('frontend/images/bg-content/cb-h5.jpg') }}") no-repeat;

        }
    </style>
@endsection
@section('content')
    <section class="no-padding sh-company-history">
        <div class="sub-header ">
            <span>OUR STORYS IN LINES</span>
            <h3>COMPANY HISTORY</h3>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('index') }}"><i class="fa fa-home"></i> HOME </a>
                </li>
                <li class="active">COMPANY HISTORY</li>
            </ol>
        </div>
    </section>
    <!-- /Sub HEader -->

    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="main-page">
                        <div class="history-list-warp">
                            @foreach ($page->pageContents as $content)
                            <div class="item-history-post">
                                <p class="title-history"><span>{{$content->title}}</span>{{$content->subtitle}}</p>
                                
                                   {!!$content->content!!}
                                
                            </div>
                            @endforeach
                           

                         

                            
                        </div>
                    </div>
                </div>
               @include('frontend.layouts.sidecontent')
            </div>
        </div>
    </section>
@endsection
