@extends('frontend.layouts.master')

@section('meta_content')
@php
    $logo=App\Helpers\MyHelper::getSiteConfig('header_site_logo');
@endphp
    <!-- HTML Meta Tags -->
    <title>{{ $page->seo_title??'' }}</title>
    <meta name="description" content="{{ $page->seo_description??'' }}">
    <meta name="keywords" content="{{$page->seo_keyword}}">
    <!-- Facebook Meta Tags -->
    <meta property="og:url" content="{{ url()->current() }}">
    <meta property="og:type" content="website">
    <meta property="og:title" content="{{ $page->seo_title }}">
    <meta property="og:description" content="{{ $page->seo_description }}">
    <meta property="og:image" content="{{ asset('storage/setting/' . $logo) }}">
    <meta property="og:image:alt" content="{{ $page->seo_title }} Logo">

    <!-- Twitter Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta property="twitter:domain" content="{{ url()->current() }}">
    <meta property="twitter:url" content="{{ url()->current() }}">
    <meta name="twitter:title" content="{{ $page->seo_title }}">
    <meta name="twitter:description" content="{{ $page->seo_description }}">
    <meta name="twitter:image" content="{{ asset('storage/setting/' . $logo) }}">
    <!-- Meta Tags Generated by Susan Paudel -->
@endsection

@section('content')
    @if(count($sliders)>0)
    <!-- Slider -->
    <section id="slider" class="no-padding">
        <div id="slide_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container">
            <!-- START REVOLUTION SLIDER 5.0.7 auto mode -->
            <div id="slider_9" class="rev_slider fullwidthabanner slider-home1" style="display:none;" data-version="5.0.7">
                <ul>
                    @foreach ($sliders as $key=>$slider)
                    <li data-title="FOCUS ON">
                        <!-- MAIN IMAGE -->
                        <img src="{{ asset('storage/slider/'.$slider->image) }}" alt=""
                            data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg"
                            data-no-retina>
                        <!-- LAYERS -->

                        <!-- LAYER NR. 1 -->
                        <div class="tp-caption tp-resizeme sl-s4-2" data-x="left" data-hoffset="0" data-y="top"
                        data-voffset="220" data-width="['400','400','400','300']" data-transform_idle="o:1;"
                        data-transform_in="{{ $key % 2 == 0 ? 'x:100px;' : 'x:-100px;' }}opacity:0;s:800;e:Power3.easeOut;"
                        data-transform_out="{{ $key % 2 == 0 ? 'x:-100px;' : 'x:100px;' }}opacity:0;s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;"
                        data-start="1500" data-whitespace="normal" data-fontsize="['32','28','21','16']"
                        data-lineheight="['32','32','26','20']" data-responsive_offset="on">
                            <p>{{$slider->title}}</p>
                        </div>
                        <!-- LAYER NR. 2 -->
                        <div class="tp-caption tp-resizeme sl-s2-2" data-x="left" data-hoffset="0" data-y="center"
                        data-voffset="['-55','-55','-75','-85']" data-width="['580','580','480','320']"
                        data-transform_idle="o:1;" data-transform_in="{{ $key % 2 == 0 ? 'x:100px;' : 'x:-100px;' }}opacity:0;s:800;e:Power3.easeOut;"
                        data-transform_out="{{ $key % 2 == 0 ? 'x:-100px;' : 'x:100px;' }}opacity:0;s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;"
                        data-start="1700" data-whitespace="['nowrap','nowrap','nowrap','normal']"
                        data-fontsize="['60','50','40','30']" data-responsive_offset="on">
                            <p>{{$slider->sub_title}}</p>
                        </div>
                        <!-- LAYER NR. 3 -->
                        <div class="tp-caption tp-resizeme sl-s3-2" data-x="left" data-hoffset="0" data-y="center"
                        data-voffset="['25','25','0','-10']" data-width="['580','580','480','300']"
                        data-transform_idle="o:1;" data-whitespace=normal
                        data-transform_in="{{ $key % 2 == 0 ? 'x:100px;' : 'x:-100px;' }}opacity:0;s:800;e:Power3.easeOut;"
                        data-transform_out="{{ $key % 2 == 0 ? 'x:-100px;' : 'x:100px;' }}opacity:0;s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;"
                        data-start="1900" data-fontsize="['16','16','15','13']" data-lineheight="['32','32','24','24']"
                        data-responsive_offset="on">
                            <p class="">{{$slider->body}}</p>
                        </div>
                        @if(isset($slider->button_one_title))
                        <!-- LAYER NR. 4 -->
                        <div class="tp-caption" data-x="left" data-hoffset="0" data-y="bottom"
                        data-voffset="['200','200','200','240']" data-transform_idle="o:1;"
                        data-transform_in="{{ $key % 2 == 0 ? 'x:100px;' : 'x:-100px;' }}opacity:0;s:800;e:Power3.easeOut;"
                        data-transform_out="{{ $key % 2 == 0 ? 'x:-100px;' : 'x:100px;' }}opacity:0;s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;"
                        data-start="2100"><a href="{{$slider->button_one_url }}" class="sl-btn-3">{{$slider->button_one_title}}</a>
                        </div>
                        @endif
                        @if(isset($slider->button_two_title))
                        <!-- LAYER NR. 5 -->
                        <div class="tp-caption" data-x="left" data-hoffset="['135','135','135','135']" data-y="bottom"
                        data-voffset="['200','200','200','240']" data-transform_idle="o:1;"
                        data-transform_in="{{ $key % 2 == 0 ? 'x:100px;' : 'x:-100px;' }}opacity:0;s:800;e:Power3.easeOut;"
                        data-transform_out="{{ $key % 2 == 0 ? 'x:-100px;' : 'x:100px;' }}opacity:0;s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;"
                        data-start="2300"><a href="{{$slider->button_two_url }}" class="sl-btn-2">{{$slider->button_two_title}}</a>
                        </div>
                        @endif
                    </li>
                    @endforeach
                    


                </ul>
            </div>
        </div>
    </section>
    <!-- /Slider -->
    @endif
    @if(isset($page->pageContents[0]))
    <section class="no-padding">
        <div class="container">
            <div class="row">
                <div class="whyus-warp-h2 cil-h5-warp">
                    <div class="col-md-6">
                        <div class="right-whyus-h2 cil-h5">
                            <div class="iconbox-warp ">
                                <div class="title-block">
                                    <span class="top-title"></span>
                                    <h2>{{$page->pageContents[0]->title??''}}</h2>
                                    <p class="sub-title">{{$page->pageContents[0]->subtitle??''}} </p>
                                    <span class="bottom-title"></span>
                                </div>
                               {!!$page->pageContents[0]->content??''!!}
                              
                                <a href="{{$page->pageContents[0]->link??'#'}}" class="ot-btn btn-sub-color">History Timeline</a>
                               
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="left-whyus-h2 right-cil-h5">
                            <img src="{{ asset('storage/pages/'.$page->pageContents[0]->image) }}" class="img-responsive"
                                alt="Image">
                            <div class="demo-style-1-box-text left" style="width: 50%;">
                                <p>{{$page->pageContents[0]->text}}</p>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
    @endif
    <!-- about description -->

    @php
    $services=App\Helpers\Helper::getServices();
    @endphp
   @if(count($services)>0)
    <section id="services" class="no-padding services-h1">
        <div class="warp-full-width bg-theme">
            <div class="title-block text-center title-on-dark title-pd">
                <span class="top-title "></span>
                <h2>Our Services</h2>
                <p class="sub-title">As always, partners grows with you!</p>
                <span class="bottom-title"></span>
            </div>
        </div>

        <div class="warp-full-width services-h1-warp">
            <div id="services-h1" class="owl-services-h1">
              
               @foreach ($services as $key=>$service)
               
                <div class="item-services">
                    <div class="iconbox-type-sm  text-center">
                        {!!$service->icon!!}
                        <h4>{{$service->title}}</h4>
                        <p>{{Str::limit($service->short_content,200)}}</p>
                        <a href="{{route('service-single',$service->slug)}}" class="ot-btn btn-border-main-color">Learn More</a>
                    </div>
                </div>
                   
                @endforeach
              
            </div>
            @if($key>3)
            <div class="customNavigation">
                <a class="btn-1 prev-services-h1"><i class="fa fa-angle-left"></i></a>
                <a class="btn-1 next-services-h1"><i class="fa fa-angle-right"></i></a>
            </div><!-- End owl button -->
            @endif
        </div>
    </section>
    @endif
    <!-- /services -->
   
    @if(count($chooses)>0)
    <section class="no-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title-block text-center title-pd">
                        <span class="top-title"></span>
                        <h2>Why to choose us</h2>
                        <p class="sub-title">As always, partners grows with you!</p>
                        <span class="bottom-title"></span>
                    </div>
                </div>
                
                <div class="warp-counter warp-counter-about-2">
                    @foreach ($chooses as $choose)
                    
                    <div class="col-md-3 col-sm-6">
                        <div class="counter-inline counter-on-light">
                            {!!$choose->icon!!}
                            <span class="counter">{{$choose->counter}}</span>
                            <p>{{$choose->title}}</p>
                        </div>
                    </div>
                        
                    @endforeach
                  
                  
                </div>
            </div>
        </div>
    </section>
    <!-- /about description -->
@endif

    <section class="no-padding bg-news-h9">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="left-fdv-h9">
                        <div class="callback-warp ">
                            <div class="title-block title-pd">
                                <span class="top-title "></span>
                                <h2>Contact US</h2>
                                <p class="sub-title">Our team will always help you</p>
                                <span class="bottom-title"></span>
                            </div>

                            <div class="form-cb-warp">
                                <form class="cb-form" method="post" action="{{route('contact-store')}}">
                                    @csrf
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="name"
                                            placeholder="Your Name*" value="{{old('full_name')}}" name="full_name" required>
                                    </div>

                                    <div class="form-group">
                                        <input type="email" name="email" value="{{old('email')}}" class="form-control" placeholder="Your Email*" required>
                                    </div>
                                    <div class="form-group">
                                        <input type="text" name="subject" value="{{old('subject')}}" class="form-control" 
                                            placeholder="Your Phone Number*" required>
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="comments"
                                            placeholder="Your Comment" value="{{old('comments')}}">
                                    </div>

                                    <button type="submit" class="btn-main-color"><i class="fa fa-paper-plane"
                                            aria-hidden="true"></i> Submit</button>
                                </form>
                            </div>

                        </div>
                    </div>
                    <div class="right-fdv-h9">
                        <img src="{{ asset('frontend/images/Content/fdv-h9.jpg') }}" class="img-responsive"
                            alt="Image">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- /Find Advisors -->

    {{-- <section>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div id="partner-h2" class="owl-partner-h2">
                        <div class="item-partner">
                            <a href="#"><img src="{{ asset('frontend/images/Partner/1.jpg') }}"
                                    class="img-responsive partner-img" alt="Image"></a>
                        </div>
                        <div class="item-partner">
                            <a href="#"><img src="{{ asset('frontend/images/Partner/2.jpg') }}"
                                    class="img-responsive partner-img" alt="Image"></a>
                        </div>
                        <div class="item-partner">
                            <a href="#"><img src="{{ asset('frontend/images/Partner/3.jpg') }}"
                                    class="img-responsive partner-img" alt="Image"></a>
                        </div>
                        <div class="item-partner">
                            <a href="#"><img src="{{ asset('frontend/images/Partner/4.jpg') }}"
                                    class="img-responsive partner-img" alt="Image"></a>
                        </div>
                        <div class="item-partner">
                            <a href="#"><img src="{{ asset('frontend/images/Partner/5.jpg') }}"
                                    class="img-responsive partner-img" alt="Image"></a>
                        </div>
                        <div class="item-partner">
                            <a href="#"><img src="{{ asset('frontend/images/Partner/6.jpg') }}"
                                    class="img-responsive partner-img" alt="Image"></a>
                        </div>
                        <div class="item-partner">
                            <a href="#"><img src="{{ asset('frontend/images/Partner/7.jpg') }}"
                                    class="img-responsive partner-img" alt="Image"></a>
                        </div>
                        <div class="item-partner">
                            <a href="#"><img src="{{ asset('frontend/images/Partner/8.jpg') }}"
                                    class="img-responsive partner-img" alt="Image"></a>
                        </div>
                        <div class="item-partner">
                            <a href="#"><img src="{{ asset('frontend/images/Partner/6.jpg') }}"
                                    class="img-responsive partner-img" alt="Image"></a>
                        </div>
                        <div class="item-partner">
                            <a href="#"><img src="{{ asset('frontend/images/Partner/7.jpg') }}"
                                    class="img-responsive partner-img" alt="Image"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section> --}}
    <!-- /Partner -->

    
@endsection
