@extends('frontend.layouts.master')
@section('meta_content')
@php
    $logo=App\Helpers\MyHelper::getSiteConfig('header_site_logo');
@endphp
  <!-- HTML Meta Tags -->
  <title>{{ $page->seo_title }} - {{ config('app.name') }}</title>
  <meta name="description" content="{{ $page->seo_description }}">
  <meta name="keywords" content="{{$page->seo_keyword}}">
  <!-- Facebook Meta Tags -->
  <meta property="og:url" content="{{ url()->current() }}">
  <meta property="og:type" content="website">
  <meta property="og:title" content="{{ $page->seo_title }} - {{ config('app.name') }}">
  <meta property="og:description" content="{{ $page->seo_description }}">
  <meta property="og:image" content="{{ asset('storage/setting/' . $logo) }}">
  <meta property="og:image:alt" content="{{ $page->seo_title }} - {{ config('app.name') }} Logo">

  <!-- Twitter Meta Tags -->
  <meta name="twitter:card" content="summary_large_image">
  <meta property="twitter:domain" content="{{ url()->current() }}">
  <meta property="twitter:url" content="{{ url()->current() }}">
  <meta name="twitter:title" content="{{ $page->seo_title }} - {{ config('app.name') }}">
  <meta name="twitter:description" content="{{ $page->seo_description }}">
  <meta name="twitter:image" content="{{ asset('storage/setting/' . $logo) }}">
  <!-- Meta Tags Generated by Susan Paudel -->
@endsection
@section('css')
    <style>
        .sh-services {
            background: url("{{ asset('frontend/images/bg-content/bg-quote-h2.jpg') }}") no-repeat;

        }

        .bg-subcr-1 {
            background: url("{{ asset('frontend/images/bg-content/bg-subcri.jpg') }}") no-repeat;

        }
    </style>
@endsection


@section('content')
    <section class="no-padding sh-services">
        <div class="sub-header ">
            <span>WHAT WE DO</span>
            <h3>OUR SERVICES</h3>
            <ol class="breadcrumb">
                <li>
                    <a href="#"><i class="fa fa-home"></i> HOME </a>
                </li>

                <li class="active">SERVICES</li>
            </ol>
        </div>
    </section>
    <!-- /subheader -->
    @if(count($services)>0)
    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="services-list-warp">
                        @foreach ($services as $service)
                        <div class="item-service-list">
                            <figure>
                                <img src="{{ asset('storage/service/'.$service->image) }}" class="img-responsive"
                                    alt="Image">
                                <figcaption>{{$service->title}}</figcaption>
                            </figure>
                            <div class="box-sum-service">
                              {!!$service->short_content!!}
                                <a href="{{route('service-single',$service->slug)}}" class="ot-btn btn-sub-color">Read More</a>
                            </div>
                        </div>
                        @endforeach
                       
                    </div>
                </div>
            </div>
        </div>
    </section>
@endif
   
@endsection
