@extends('frontend.layouts.master')

@section('css')
    <style>
        .sh-single-services {
            background: url("{{ asset('frontend/images/bg-content/sh-single-services.jpg') }}") no-repeat;

        }

        .bg-subcr-1 {
            background: url("{{ asset('frontend/images/bg-content/bg-subcri.jpg') }}") no-repeat;

        }
    </style>
@endsection
@section('meta_content')
  <!-- HTML Meta Tags -->
  <title>{{ $service->seo_title??$service->title }} - {{ config('app.name') }}</title>
  <meta name="description" content="{{ $service->seo_description }}">
  <meta name="keywords" content="{{$service->seo_keyword}}">
  <!-- Facebook Meta Tags -->
  <meta property="og:url" content="{{ url()->current() }}">
  <meta property="og:type" content="website">
  <meta property="og:title" content="{{ $service->seo_title }} - {{ config('app.name') }}">
  <meta property="og:description" content="{{ $service->seo_description }}">
  <meta property="og:image" content="{{ asset('storage/blog/' . $service->image) }}">
  <meta property="og:image:alt" content="{{ $service->seo_title }} - {{ config('app.name') }} Logo">

  <!-- Twitter Meta Tags -->
  <meta name="twitter:card" content="summary_large_image">
  <meta property="twitter:domain" content="{{ url()->current() }}">
  <meta property="twitter:url" content="{{ url()->current() }}">
  <meta name="twitter:title" content="{{ $service->seo_title }} - {{ config('app.name') }}">
  <meta name="twitter:description" content="{{ $service->seo_description }}">
  <meta name="twitter:image" content="{{ asset('storage/blog/' . $service->image) }}">
  <!-- Meta Tags Generated by Susan Paudel -->
@endsection

@section('content')
    <section class="no-padding sh-single-services">
        <div class="sub-header ">
            <span>WHAT WE DO</span>
            <h3>{{$service->title}}</h3>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('index') }}"><i class="fa fa-home"></i> HOME </a>
                </li>
                <li>
                    <a href="{{route('service')}}"> SERVICES </a>
                </li>
                <li class="active">{{$service->title}}</li>
            </ol>
        </div>
    </section>
    <!-- /Sub HEader -->

    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="services-2-detail-warp">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="title-block title-contact">
                                    <h3>Overview</h3>
                                    <span class="bottom-title"></span>
                                </div>

                                {!!$service->content!!}

                            </div>

                        </div>
                    </div>

                    @if(count($traders)>0)
                    <div class="benefit-services-warp-2 desk-pdt-60">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="title-block title-contact">
                                    <h3>Why Traders Choose Us</h3>
                                    <span class="bottom-title"></span>
                                </div>
                            </div>
                            @foreach ($traders as $trader)
                            <div class="col-md-4">
                                <div class="iconbox">
                                    {!!$trader->icon!!}
                                    <h4>{{$trader->title}}</h4>
                                    {{$trader->description}}
                                </div>
                            </div>
                            @endforeach
                            
                           
                        </div>
                    </div>
                    @endif
                    @if(count($client_benefit_titles)>0)
                    <div class="strategy-services-3-warp desk-pdt-60">
                        <div class="title-block title-contact">
                            <h3>How Clients Benefits</h3>
                            <span class="bottom-title"></span>
                        </div>
                        <div class="statements-accordion">
                            <div class="panel-group accordion-2" id="accordion">
                                @foreach ($client_benefit_titles as $key => $title)
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                <a class="accordion-toggle @if($key != 0) collapsed @endif" data-toggle="collapse" data-parent="#accordion" href="#collapse{{$key}}">
                                                    {{$title}}
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="collapse{{$key}}" class="panel-collapse collapse @if($key == 0) in @endif">
                                            <div class="panel-body">
                                                {{$client_benefit_descriptions[$key] ?? 'Description not available'}}
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                            
                           
                        </div>
                    </div>
                    @endif
                </div>
                @include('frontend.layouts.sidecontent')
            </div>
        </div>
    </section>
@endsection
