@extends('frontend.layouts.master')
@section('meta_content')
@php
    $logo=App\Helpers\MyHelper::getSiteConfig('header_site_logo');
@endphp
  <!-- HTML Meta Tags -->
  <title>{{ $page->seo_title }} - {{ config('app.name') }}</title>
  <meta name="description" content="{{ $page->seo_description }}">
  <meta name="keywords" content="{{$page->seo_keyword}}">
  <!-- Facebook Meta Tags -->
  <meta property="og:url" content="{{ url()->current() }}">
  <meta property="og:type" content="website">
  <meta property="og:title" content="{{ $page->seo_title }} - {{ config('app.name') }}">
  <meta property="og:description" content="{{ $page->seo_description }}">
  <meta property="og:image" content="{{ asset('storage/setting/' . $logo) }}">
  <meta property="og:image:alt" content="{{ $page->seo_title }} - {{ config('app.name') }} Logo">

  <!-- Twitter Meta Tags -->
  <meta name="twitter:card" content="summary_large_image">
  <meta property="twitter:domain" content="{{ url()->current() }}">
  <meta property="twitter:url" content="{{ url()->current() }}">
  <meta name="twitter:title" content="{{ $page->seo_title }} - {{ config('app.name') }}">
  <meta name="twitter:description" content="{{ $page->seo_description }}">
  <meta name="twitter:image" content="{{ asset('storage/setting/' . $logo) }}">
  <!-- Meta Tags Generated by Susan Paudel -->
@endsection
@section('css')
    <style>
        .sh-team {
            background: url("{{ asset('frontend/images/bg-content/sh-team.jpg') }}") no-repeat;

        }

        .bg-subcr-1 {
            background: url("{{ asset('frontend/images/bg-content/bg-subcri.jpg') }}") no-repeat;

        }
    </style>
@endsection

@section('content')
    <section class="no-padding sh-team">
        <div class="sub-header ">
            <span>CONNECT WITH US</span>
            <h3>OUR TEAMS</h3>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('index') }}"><i class="fa fa-home"></i> HOME </a>
                </li>

                <li class="active">OUR TEAM</li>
            </ol>
        </div>
    </section>
    <!-- /subheader -->
   
    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="main-page">
                        @if(count($top_teams)>0)
                        <div class="about-founder">
                            <div class="box-img-left">
                                @foreach ($top_teams as $t_team)
                                <div class="col-md-6 col-sm-6">
                                    <div class="item-team">
                                        <img src="{{ asset('storage/team/'.$t_team->image) }}"
                                            class="img-responsive" alt="{{$t_team->name}}">
                                        <div class="body-team">
                                            <h4>{{$t_team->name}}</h4>
                                            <p>{{$t_team->employee_type}}</p>
                                        </div>
                                        <div class="footer-team">
                                           
                                            <a class="facebook" href="{{$t_team->facebook??'#'}}" target="_blank"><i class="fa fa-facebook"
                                                    aria-hidden="true"></i></a>
                                        
                                           
                                            <a class="twitter" href="{{$t_team->twitter??'#'}}" target="_blank"><i class="fa fa-twitter"
                                                    aria-hidden="true"></i></a>
                                          
                                            <a class="google" href="{{$t_team->google??'#'}}" target="_blank"><i class="fa fa-google-plus"
                                                    aria-hidden="true"></i></a>
                                           
                                            <a class="linkedin" href="{{$t_team->linkedin??'#'}}" target="_blank"><i class="fa fa-linkedin"
                                                    aria-hidden="true"></i></a>
                                            
                                        </div>
                                    </div>
                                </div>
                                    
                                @endforeach
                            </div>
                        </div>
                        @endif
                        <!-- /about founder -->
                        <div class="ourteam-page">
                            <div class="title-block text-center title-pd ">
                                <span class="top-title"></span>
                                <h2>Our Team</h2>
                                <p class="sub-title">As always, partners grows with you!</p>
                                <span class="bottom-title"></span>
                            </div>
                            @if(count($buttom_teams)>0)
                            <div class="row">
                                @foreach ($buttom_teams as $team)
                                <div class="col-md-4 col-sm-6">
                                    <div class="item-team">
                                        <img src="{{ asset('storage/team/'.$team->image) }}"
                                        class="img-responsive" alt="{{$team->name}}">
                                        <div class="body-team">
                                            <h4>{{$team->name}}</h4>
                                            <p>{{$team->employee_type}}</p>
                                        </div>
                                        <div class="footer-team">
                                           
                                            <a class="facebook" href="{{$team->facebook??'#'}}" target="_blank"><i class="fa fa-facebook"
                                                    aria-hidden="true"></i></a>
                                        
                                           
                                            <a class="twitter" href="{{$team->twitter??'#'}}" target="_blank"><i class="fa fa-twitter"
                                                    aria-hidden="true"></i></a>
                                          
                                            <a class="google" href="{{$team->google??'#'}}" target="_blank"><i class="fa fa-google-plus"
                                                    aria-hidden="true"></i></a>
                                           
                                            <a class="linkedin" href="{{$team->linkedin??'#'}}" target="_blank"><i class="fa fa-linkedin"
                                                    aria-hidden="true"></i></a>
                                            
                                        </div>
                                    </div>
                                </div>
                                  
                                @endforeach
                            </div>
                            @endif
                        </div>
                    </div>
                </div>
              

                @include('frontend.layouts.sidecontent')
            </div>
        </div>
    </section>
@endsection
